### ISSUE TITLE
Error Reading Directory Strucutre

### ISSUE THREAD

**Issue by mubaidr** [subucodes/vscode-ext-project-structure-extractor#1]
When using on Linux Open Suse, tumbleweed. I got the following error. 

![Screenshot_20241229_153542](https://github.com/user-attachments/assets/a5a01321-7bbe-4170-92a1-0383f448dda1)

**Comment by mubaidr** [comment]
I think we can just use default vscode copy to clipboard feature? 

https://github.com/subucodes/vscode-ext-project-structure-extractor/blob/dbd38e4df767ed5e04902a25cedc39be1313e6e6/extension.js#L206

```js
await vscode.env.clipboard.writeText(text)
```

**Comment by subucodes** [comment]
@mubaidr I will try with this suggestion and test on this specific distro.

**Comment by subucodes** [comment]
I have now used the vscode clipboard instead of custom one. @mubaidr Please use the 0.0.3 version and let me know how it goes.
![image](https://github.com/user-attachments/assets/5f329284-5881-4adc-9152-ceff4bdd0fac)
