### ISSUE TITLE
[Feature] Option to ignore files? List only directories

### ISSUE THREAD

**Issue by mubaidr** [subucodes/vscode-ext-project-structure-extractor#2]
Can you please add option to ignore files? Like if we only need to list directories?

**Comment by subucodes** [comment]
It is available in 0.0.3 version
![image](https://github.com/user-attachments/assets/d4057be2-f095-4cfa-939f-55700d142cdd)
![image](https://github.com/user-attachments/assets/c7bfb288-0487-4cd5-9ec6-f32a25d929be)

@mubaidr Let me know how it goes.

**Comment by mubaidr** [comment]
Awesome man! Thanks
